In [2]:
import numpy as np

## Note

1. 모든 답은 `x` 변수에 assign 해주세요. e.g., `x = np.array([1,2,3])`

### 1. array 만들기

가장 기본적이지만, 가장 자주 쓰이는 array 만드는 방법 몇가지부터 연습해보겠습니다.

In [3]:
# 1. 다음과 같이 생긴 어레이를 만들어보세요. (hint: np.array)
#
#           array([[1, 2, 3],
#                  [4, 5, 6]])
#
# ---------------------- TODO ---------------------- #
#                                                    #
x = np.array([[1, 2, 3],[4, 5, 6]])      
#                         #
#                                                    #
# -------------------------------------------------- #
print('# 1')
print(x)
print()

# 1
[[1 2 3]
 [4 5 6]]



In [4]:
# 2. shape이 (2,3)인 제로행렬을 만들어 보세요.  (hint: np.zeros)
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.zeros([2,3])
#                                                    #
# -------------------------------------------------- #
print('# 2')
print(x)
print()

# 2
[[0. 0. 0.]
 [0. 0. 0.]]



In [5]:
# 3. shape이 (2,3)이고 모든 원소가 3인 행렬을 만들어 보세요.  (hint: np.full)
# ---------------------- TODO ---------------------- #
#                                                    #
x = 3 * np.ones([2,3])
#                                                    #
# -------------------------------------------------- #
print('# 3')
print(x)
print()

# 3
[[3. 3. 3.]
 [3. 3. 3.]]



In [6]:
# 4. shape이 (2,3)인 랜덤 행렬을 만들어 보세요.  (hint: np.random.randn)
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.random.randn(6).reshape([2,3])
#                                                    #
# -------------------------------------------------- #
print('# 4')
print(x)
print()

# 4
[[ 1.28587132 -0.17990778  0.20289596]
 [ 0.04402351 -1.36521753  0.41280623]]



In [7]:
# 5. shape이 (2,3)인 랜덤 "정수" 행렬을 만들어 보세요.   (hint: np.random.randint)
# 각 원소의 값은 -10부터 10 사이로 지정 해주세요.
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.random.randint(-10,10,6).reshape([2,3])

#                                                    #
# -------------------------------------------------- #
print('# 5')
print(x)
print()

# 5
[[  4  -2   5]
 [ -5  -1 -10]]



### 2. Indexing & Slicing 연습

In [34]:
A = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

B = np.array([
    [0,3,0],
    [7,0,0],
    [0,0,1]
])

In [35]:
# 1. A 행렬에서 1번 행에 접근하려면 어떻게 해야 할까요?
#   주의: 숫자는 항상 0부터 시작합니다. 따라서 1행은 [6,5,4] 행을 의미합니다.
# ---------------------- TODO ---------------------- #
#                                                    #
x= A[1]
#                                                    #
# -------------------------------------------------- #
print('# 1')
print(x)
print()

# 1
[6 5 4]



In [36]:
# 2. A 행렬에서 원소 '4'에 접근하려면 어떻게 해야 할까요? '4'는 1행 2열에 있습니다.
# ---------------------- TODO ---------------------- #
#                                                    #
x=A[1,2]
#                                                    #
# -------------------------------------------------- #
print('# 2')
print(x)
print()

# 2
4



In [37]:
# 3. A 행렬에서 2번 열에 접근하려면 어떻게 해야 할까요?
#   주의: 넘파이에서 1차원 벡터는 원래 데이터가 행이든 열이든 항상 row vector로 나옵니다.
#
#   따라서 desired output은 [7 4 1] 입니다.
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=A[:,2]
#                                                    #
# -------------------------------------------------- #
print('# 3')
print(x)
print()

# 3
[7 4 1]



In [38]:
# 4. A 행렬에서 1~2행 & 0~1열을 뽑으려면 어떻게 해야 할까요?
#
#   desired output: [[6 5]
#                    [3 2]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=A[1:3,0:2]
#                                                    #
# -------------------------------------------------- #
print('# 4')
print(x)
print()

# 4
[[6 5]
 [3 2]]



In [62]:
# 5. (고급 인덱싱) B 행렬에서 0이 아닌 원소들을 전부 뽑고 싶습니다. 어떻게 해야 할까요?
#   좌표는 다음과 같습니다: ([0,1], [1,0], [2,2])
#   c.f. https://docs.scipy.org/doc/numpy-1.15.0/user/basics.indexing.html#indexing-multi-dimensional-arrays
#   Note: 4번과 대조해보세요. 행렬 안에서 작은 '행렬'을 추출 할때와, 여기저기서 '원소'를 추출 할때의 syntax가 다릅니다!
#
#   desired output: [3 7 1]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=list(map(lambda x : B[x[0],x[1]],np.argwhere(B)))
#                                                    #
# -------------------------------------------------- #
print('# 5')
print(x)
print()

# 5
[3, 7, 1]



In [14]:
# 6. (고급 인덱싱) B 행렬에서 0이 아닌 원소들의 좌표들을 전부 뽑고 싶습니다. 어떻게 해야 할까요? (hint: np.argwhere)
#
#   desired output: [[0 1]
#                    [1 0]
#                    [2 2]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.argwhere(B)
#                                                    #
# -------------------------------------------------- #
print('# 6')
print(x)
print()

# 6
[[0 1]
 [1 0]
 [2 2]]



In [15]:
# 7. (고급 인덱싱) B 행렬에서 2보다 큰 원소들의 좌표들을 전부 뽑고 싶습니다. 어떻게 해야 할까요? (hint: np.argwhere)
#   어려우시면 (B > 2) 를 한번 출력해보세요. 그리고 파이썬에서 True는 1, False는 0으로 취급될 수 있습니다. (자세한건 truthy, falsy 검색)
#
#   desired output: [[0 1]
#                    [1 0]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.argwhere(B>2)
#                                                    #
# -------------------------------------------------- #
print('# 7')
print(x)
print()

# 7
[[0 1]
 [1 0]]



### 3. Axis 관련 연습

In [63]:
A = np.array([  # A.shape == (3,3)
    [1,0,0],
    [1,0,0],
    [0,0,1]
])

B = np.array([  # B.shape == (2,2,3)
    [
        [ 0, 1, 2],
        [ 3, 4, 5]
    ],
    [
        [ 6, 7, 8],
        [ 9,10,11]
    ]
])

In [64]:
# 1. A의 각 행을 합한 벡터를 만들어 보세요. (가로로 더합니다) (hint: A.sum())
#
#   desired output: [1 1 1]  (가로로 더했지만 넘파이는 기본적으로 row vector로 반환합니다)
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=A.sum(axis=1)
#                                                    #
# -------------------------------------------------- #
print('# 1')
print(x)
print()

# 1
[1 1 1]



In [65]:
# 2. A의 각 행을 합한 벡터를 열벡터로 나오게 보세요. (1번에서 쓴 함수에 parameter 하나만 수정하면 됩니다.)
#    Note: sum 뿐만이 아니라 형태를 유지했으면 좋겠다.. 싶은 함수들은 찾아보면 대부분 이 parameter가 존재합니다.
#    c.f. https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html
#
#   desired output: [[1]
#                    [1]
#                    [1]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=A.sum(axis=1, keepdims= True)
#                                                    #
# -------------------------------------------------- #
print('# 2')
print(x)
print()

# 2
[[1]
 [1]
 [1]]



In [66]:
# 3. B의 1번 축을 기준으로 평균을 내보세요. (그리고 왜 그렇게 나왔을지 생각해보세요)
#
#   desired output: [[1.5 2.5 3.5]
#                    [7.5 8.5 9.5]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=B.mean(axis=1)
#                                                    #
# -------------------------------------------------- #
print('# 3')
print(x)
print('x.shape ==', x.shape)
print()

# 3
[[1.5 2.5 3.5]
 [7.5 8.5 9.5]]
x.shape == (2, 3)



In [67]:
# 4. 3번에 keepdims 를 True로 놓고 다시 돌려보세요. 3번의 결과와 shape의 차이를 보세요.
#
#    Note: 넘파이의 다차원 배열들은 2차원으로 project 해서 보여줄 수 밖에 없는 한계 때문에
#          시각적으로 이해하기가 어려울 때가 있습니다. 그럴때 shape을 보면서 디버깅
#          하는게 개인적으로 굉장히 편한것 같습니다.
#
#   desired output: [[[1.5 2.5 3.5]]
#
#                    [[7.5 8.5 9.5]]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=B.mean(axis=1,keepdims=1)
#                                                    #
# -------------------------------------------------- #
print('# 4')
print(x)
print('x.shape ==', x.shape)
print()

# 4
[[[1.5 2.5 3.5]]

 [[7.5 8.5 9.5]]]
x.shape == (2, 1, 3)



array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

In [78]:
# 5. B의 1번과 2번 축을 서로 바꿔보세요.    (hint: B.transpose())
#   Note: shape 기준으로 (2,2,3) --> (2,3,2)
#
#   desired output:   [[[ 0  3]
#                       [ 1  4]
#                       [ 2  5]]
#
#                      [[ 6  9]
#                       [ 7 10]
#                       [ 8 11]]]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=np.transpose(B,(0,2,1))
#                                                    #
# -------------------------------------------------- #
print('# 5')
print(x)
print()

# 5
[[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]



In [83]:
# 6. B 행렬의 shape 맨앞에 새로운 축을 추가해보세요. (None / np.newaxis)
#   c.f. https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#numpy.newaxis
#
#   desired output: shape 기준으로 (2,2,3) --> (1,2,2,3)
#
# ---------------------- TODO ---------------------- #
#                                                    #
x = B[np.newaxis,:]
#                                                    #
# -------------------------------------------------- #
print('# 6')
print('x.shape == ', x.shape)
print()

# 6
x.shape ==  (1, 2, 2, 3)



In [84]:
# 7. 새로운 축을 B의 1번 축으로 추가해보세요.
#
#   desired output: shape 기준으로 (2,2,3) --> (2,1,2,3)
#
# ---------------------- TODO ---------------------- #
#                                                    #
x = B[:,np.newaxis]
#                                                    #
# -------------------------------------------------- #
print('# 7')
print('x.shape == ', x.shape)
print()

# 7
x.shape ==  (2, 1, 2, 3)



### 4. 자주 쓰이는 함수들

In [28]:
np.random.seed(1)  # random number generation을 위한 seed 값을 설정해줍니다.
                   # 디버깅을 하거나, 아니면 지금처럼 이 주피터 파일을 돌리는 유저들이
                   # 전부 같은 결과를 얻게 하기위해 사용합니다.

arr = np.arange(12)
mat = np.random.randint(1,10, (2,3))

print("arr:", arr)
print("mat:")
print(mat)

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
mat:
[[6 9 6]
 [1 1 2]]


In [29]:
# 1. arr를 (3, 4)로 shape을 변환해보세요
# ---------------------- TODO ---------------------- #
#                                                    #
x=arr.reshape([3,4])
#                                                    #
# -------------------------------------------------- #
print('# 1')
print('x.shape == ', x.shape)
print()

# 1
x.shape ==  (3, 4)



In [30]:
# 2. mat의 행마다 가장 큰 값을 뽑아보세요.
#
#   desired output: [9 2]
#
# ---------------------- TODO ---------------------- #
#                                                    #
x=mat.max(axis=1)
#                                                    #
# -------------------------------------------------- #
print('# 1')
print(x)
print()

# 1
[9 2]



### 마치며...

1. [레퍼런스 페이지](https://docs.scipy.org/doc/numpy/)를 꼭 활용하세요!
2. 수치를 다루다가 '이런 함수 있으면 편할거같은데..' 싶어서 찾아보면 넘파이에 거의 다 있습니다! 구글링 꼭 하세요!
3. 결국은 짬입니다. 많이 써보는게 답입니다.